# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-06 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ceo',
            fields=[
                ('c_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=20)),
                ('c_sex', models.IntegerField(null=True)),
                ('c_phone', models.CharField(max_length=20, null=True)),
                ('c_email', models.CharField(max_length=30, null=True)),
                ('c_photo', models.CharField(max_length=200, null=True)),
                ('c_password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CostTask',
            fields=[
                ('ct_id', models.AutoField(primary_key=True, serialize=False)),
                ('ct_type', models.IntegerField(null=True)),
                ('ct_comment', models.CharField(max_length=200, null=True)),
                ('ct_amount', models.FloatField(null=True)),
                ('ct_dept_name', models.CharField(max_length=20, null=True)),
                ('ct_sponsor', models.CharField(max_length=10, null=True)),
                ('ct_straight_upper', models.CharField(max_length=10, null=True)),
                ('ct_create_date', models.DateField(null=True)),
                ('ct_submit_date', models.DateField(null=True)),
                ('ct_approve_date', models.DateField(null=True)),
                ('ct_status', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('d_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('e_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('e_name', models.CharField(max_length=20)),
                ('e_sex', models.IntegerField(null=True)),
                ('e_job', models.CharField(max_length=20, null=True)),
                ('e_phone', models.CharField(max_length=20, null=True)),
                ('e_email', models.CharField(max_length=30, null=True)),
                ('e_photo', models.CharField(max_length=200, null=True)),
                ('e_password', models.CharField(max_length=20)),
                ('e_register_time', models.DateTimeField()),
                ('e_dept_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oa_core.Department')),
            ],
        ),
        migrations.CreateModel(
            name='HolidayTask',
            fields=[
                ('ht_id', models.AutoField(primary_key=True, serialize=False)),
                ('ht_type', models.IntegerField(null=True)),
                ('ht_start_date', models.DateField(null=True)),
                ('ht_end_date', models.DateField(null=True)),
                ('ht_days', models.IntegerField(null=True)),
                ('ht_comment', models.CharField(max_length=200, null=True)),
                ('ht_dept_name', models.CharField(max_length=20, null=True)),
                ('ht_sponsor', models.CharField(max_length=10, null=True)),
                ('ht_straight_upper', models.CharField(max_length=10, null=True)),
                ('ht_create_date', models.DateField(null=True)),
                ('ht_submit_date', models.DateField(null=True)),
                ('ht_approve_date', models.DateField(null=True)),
                ('ht_status', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('m_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('m_name', models.CharField(max_length=20)),
                ('m_sex', models.IntegerField(null=True)),
                ('m_phone', models.CharField(max_length=20, null=True)),
                ('m_email', models.CharField(max_length=30, null=True)),
                ('m_photo', models.CharField(max_length=200, null=True)),
                ('m_password', models.CharField(max_length=20)),
                ('m_ceo_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oa_core.Ceo')),
                ('m_dept_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oa_core.Department')),
            ],
        ),
        migrations.CreateModel(
            name='OvertimeTask',
            fields=[
                ('ot_id', models.AutoField(primary_key=True, serialize=False)),
                ('ot_start_dateTime', models.DateTimeField(null=True)),
                ('ot_end_dateTime', models.DateTimeField(null=True)),
                ('ot_hours', models.IntegerField(null=True)),
                ('ot_comment', models.CharField(max_length=200, null=True)),
                ('ot_dept_name', models.CharField(max_length=20, null=True)),
                ('ot_sponsor', models.CharField(max_length=10, null=True)),
                ('ot_straight_upper', models.CharField(max_length=10, null=True)),
                ('ot_create_date', models.DateField(null=True)),
                ('ot_submit_date', models.DateField(null=True)),
                ('ot_approve_date', models.DateField(null=True)),
                ('ot_status', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='d_manager_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oa_core.Manager'),
        ),
    ]
