# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-13 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oa_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceo',
            name='c_photo',
            field=models.ImageField(null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_photo',
            field=models.ImageField(null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='m_photo',
            field=models.ImageField(null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
