# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oa_core', '0003_auto_20180417_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='dept_id',
            new_name='dept',
        ),
        migrations.RenameField(
            model_name='manager',
            old_name='ceo_id',
            new_name='ceo',
        ),
        migrations.RemoveField(
            model_name='department',
            name='manager_id',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='dept_id',
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_of', to='oa_core.Manager'),
        ),
        migrations.AddField(
            model_name='manager',
            name='dept',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dept_of', to='oa_core.Department'),
        ),
    ]
