# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oa_core', '0005_auto_20180417_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overtimetask',
            old_name='end_dateTime',
            new_name='end_datetime',
        ),
        migrations.RenameField(
            model_name='overtimetask',
            old_name='start_dateTime',
            new_name='start_datetime',
        ),
    ]
