# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oa_core', '0006_auto_20180418_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overtimetask',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='overtimetask',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='overtimetask',
            name='end_hour',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='overtimetask',
            name='overtime_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='overtimetask',
            name='start_hour',
            field=models.IntegerField(null=True),
        ),
    ]
