# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oa_core', '0007_auto_20180418_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costtask',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='holidaytask',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='overtimetask',
            name='create_date',
        ),
        migrations.AddField(
            model_name='costtask',
            name='create_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='holidaytask',
            name='create_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='overtimetask',
            name='create_date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
