# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oa_core', '0008_auto_20180426_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costtask',
            name='approve_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='costtask',
            name='submit_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='holidaytask',
            name='approve_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='holidaytask',
            name='submit_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='overtimetask',
            name='approve_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='overtimetask',
            name='submit_date',
            field=models.DateTimeField(null=True),
        ),
    ]
