# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-12 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oa_core', '0010_auto_20180501_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceo',
            name='dept',
            field=models.CharField(default='CEO', max_length=20),
        ),
    ]
