# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-23 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oa_core', '0011_ceo_dept'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CostTask',
        ),
        migrations.RemoveField(
            model_name='department',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='dept',
        ),
        migrations.DeleteModel(
            name='HolidayTask',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='ceo',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='dept',
        ),
        migrations.DeleteModel(
            name='OvertimeTask',
        ),
        migrations.DeleteModel(
            name='Ceo',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
