# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-23 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oa_core', '0012_auto_20180523_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ceo',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('sex', models.IntegerField(null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('photo', models.ImageField(null=True, upload_to='uploads/%Y/%m/%d/')),
                ('password', models.CharField(max_length=20)),
                ('dept', models.CharField(default='CEO', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CostTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField(null=True)),
                ('comment', models.CharField(max_length=200, null=True)),
                ('amount', models.FloatField(null=True)),
                ('dept_name', models.CharField(max_length=20, null=True)),
                ('sponsor', models.CharField(max_length=10, null=True)),
                ('straight_upper', models.CharField(max_length=10, null=True)),
                ('create_date_time', models.DateTimeField(null=True)),
                ('submit_date_time', models.DateTimeField(null=True)),
                ('approve_date_time', models.DateTimeField(null=True)),
                ('status', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('sex', models.IntegerField(null=True)),
                ('job', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('photo', models.ImageField(null=True, upload_to='uploads/%Y/%m/%d/')),
                ('password', models.CharField(max_length=20)),
                ('register_time', models.DateTimeField()),
                ('dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oa_core.Department')),
            ],
        ),
        migrations.CreateModel(
            name='HolidayTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField(null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('days', models.IntegerField(null=True)),
                ('comment', models.CharField(max_length=200, null=True)),
                ('dept_name', models.CharField(max_length=20, null=True)),
                ('sponsor', models.CharField(max_length=10, null=True)),
                ('straight_upper', models.CharField(max_length=10, null=True)),
                ('create_date_time', models.DateTimeField(null=True)),
                ('submit_date_time', models.DateTimeField(null=True)),
                ('approve_date_time', models.DateTimeField(null=True)),
                ('status', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('sex', models.IntegerField(null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('photo', models.ImageField(null=True, upload_to='uploads/%Y/%m/%d/')),
                ('password', models.CharField(max_length=20)),
                ('ceo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='oa_core.Ceo')),
                ('dept', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dept_of', to='oa_core.Department')),
            ],
        ),
        migrations.CreateModel(
            name='OvertimeTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('overtime_date', models.DateField(null=True)),
                ('start_hour', models.IntegerField(null=True)),
                ('end_hour', models.IntegerField(null=True)),
                ('hours', models.IntegerField(null=True)),
                ('comment', models.CharField(max_length=200, null=True)),
                ('dept_name', models.CharField(max_length=20, null=True)),
                ('sponsor', models.CharField(max_length=10, null=True)),
                ('straight_upper', models.CharField(max_length=10, null=True)),
                ('create_date_time', models.DateTimeField(null=True)),
                ('submit_date_time', models.DateTimeField(null=True)),
                ('approve_date_time', models.DateTimeField(null=True)),
                ('status', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_of', to='oa_core.Manager'),
        ),
    ]
